require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SurgicalProceduresController do
  before :each do
    create_and_sign_in
  end
  # This should return the minimal set of attributes required to create a valid
  # SurgicalProcedure. As you add validations to SurgicalProcedure, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SurgicalProceduresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all surgical_procedures as @surgical_procedures" do
      surgical_procedure = SurgicalProcedure.create! valid_attributes
      get :index, {}, valid_session
      assigns(:surgical_procedures).should eq([surgical_procedure])
    end
  end

  describe "GET show" do
    it "assigns the requested surgical_procedure as @surgical_procedure" do
      surgical_procedure = SurgicalProcedure.create! valid_attributes
      get :show, {:id => surgical_procedure.to_param}, valid_session
      assigns(:surgical_procedure).should eq(surgical_procedure)
    end
  end

  describe "GET new" do
    it "assigns a new surgical_procedure as @surgical_procedure" do
      get :new, {}, valid_session
      assigns(:surgical_procedure).should be_a_new(SurgicalProcedure)
    end
  end

  describe "GET edit" do
    it "assigns the requested surgical_procedure as @surgical_procedure" do
      surgical_procedure = SurgicalProcedure.create! valid_attributes
      get :edit, {:id => surgical_procedure.to_param}, valid_session
      assigns(:surgical_procedure).should eq(surgical_procedure)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SurgicalProcedure" do
        expect {
          post :create, {:surgical_procedure => valid_attributes}, valid_session
        }.to change(SurgicalProcedure, :count).by(1)
      end

      it "assigns a newly created surgical_procedure as @surgical_procedure" do
        post :create, {:surgical_procedure => valid_attributes}, valid_session
        assigns(:surgical_procedure).should be_a(SurgicalProcedure)
        assigns(:surgical_procedure).should be_persisted
      end

      it "redirects to the created surgical_procedure" do
        post :create, {:surgical_procedure => valid_attributes}, valid_session
        response.should redirect_to(SurgicalProcedure.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved surgical_procedure as @surgical_procedure" do
        # Trigger the behavior that occurs when invalid params are submitted
        SurgicalProcedure.any_instance.stub(:save).and_return(false)
        post :create, {:surgical_procedure => { "name" => "invalid value" }}, valid_session
        assigns(:surgical_procedure).should be_a_new(SurgicalProcedure)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SurgicalProcedure.any_instance.stub(:save).and_return(false)
        post :create, {:surgical_procedure => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested surgical_procedure" do
        surgical_procedure = SurgicalProcedure.create! valid_attributes
        # Assuming there are no other surgical_procedures in the database, this
        # specifies that the SurgicalProcedure created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SurgicalProcedure.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => surgical_procedure.to_param, :surgical_procedure => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested surgical_procedure as @surgical_procedure" do
        surgical_procedure = SurgicalProcedure.create! valid_attributes
        put :update, {:id => surgical_procedure.to_param, :surgical_procedure => valid_attributes}, valid_session
        assigns(:surgical_procedure).should eq(surgical_procedure)
      end

      it "redirects to the surgical_procedure" do
        surgical_procedure = SurgicalProcedure.create! valid_attributes
        put :update, {:id => surgical_procedure.to_param, :surgical_procedure => valid_attributes}, valid_session
        response.should redirect_to(surgical_procedure)
      end
    end

    describe "with invalid params" do
      it "assigns the surgical_procedure as @surgical_procedure" do
        surgical_procedure = SurgicalProcedure.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SurgicalProcedure.any_instance.stub(:save).and_return(false)
        put :update, {:id => surgical_procedure.to_param, :surgical_procedure => { "name" => "invalid value" }}, valid_session
        assigns(:surgical_procedure).should eq(surgical_procedure)
      end

      it "re-renders the 'edit' template" do
        surgical_procedure = SurgicalProcedure.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SurgicalProcedure.any_instance.stub(:save).and_return(false)
        put :update, {:id => surgical_procedure.to_param, :surgical_procedure => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested surgical_procedure" do
      surgical_procedure = SurgicalProcedure.create! valid_attributes
      expect {
        delete :destroy, {:id => surgical_procedure.to_param}, valid_session
      }.to change(SurgicalProcedure, :count).by(-1)
    end

    it "redirects to the surgical_procedures list" do
      surgical_procedure = SurgicalProcedure.create! valid_attributes
      delete :destroy, {:id => surgical_procedure.to_param}, valid_session
      response.should redirect_to(surgical_procedures_url)
    end
  end

end
